name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Paso de checkout para obtener el código del repositorio
    - name: Check out the repository
      uses: actions/checkout@v2

    # Paso para listar los archivos en la raíz del repositorio
    - name: List files in root
      run: |
        ls -la

    # Paso para hacer login en Docker Hub
    - name: Docker Login
      env:          
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando Login"         
        echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
        echo "Fin del login"

    # Paso para construir la imagen de Docker usando el Dockerfile en la raíz
    - name: Build Docker Image
      run: |
        docker build -t alorpes/cron-ticket:0.0.1 .

    # Paso para hacer push de la imagen a Docker Hub
    - name: Push Docker Image
      run: |
        docker push alorpes/cron-ticket:0.0.1
