name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso de checkout para obtener el código del repositorio
      - name: Check out the repository
        uses: actions/checkout@v2

      # Paso para hacer login en Docker Hub
      - name: Docker Login
        env:          
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      # Paso para construir y hacer push de la imagen de Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t alorpes/cron-ticket:0.0.1 .
          docker push alorpes/cron-ticket:0.0.1
