name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Docker Logi
      env:          
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando Login"         
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
        
    - name: Build Docker Image
      run: |
        docker build -t alorpes/cron-ticket:0.0.1 .
        
    - name: Push Docker Image
      run: |
        docker push alorpes/cron-ticket:0.0.1
